site_name: OpenScope Community Predictive Processing
site_url: https://allenneuraldynamics.github.io/openscope-community-predictive-processing/
use_directory_urls: true
nav:
- Home: index.md
- Project Plan:
  - Overview: experimental-plan.md
  - Experimental Plan: detailed-experimental-plan.md
  - Analysis Plan: analysis-plan.md
- Project Resources:
  - Experiment Summary: experiment-summary.md
  - Stimuli:
    - Introduction to Bonsai: stimuli/bonsai_introduction.md
    - Bonsai Instructions: stimuli/bonsai_instructions.md
    - Bonsai for Python Programmers: stimuli/bonsai_for_python_programmers.md
    - List of scripts: stimuli/list_scripts.md
    - Standard Oddball: stimuli/standard-oddball.md
    - Standard Oddball Jitter Random: stimuli/standard-oddball-jitter-random.md
    - Sensory-Motor Closed-Loop: stimuli/sensory-motor-closed-loop.md
    - Sequence Mismatch: stimuli/sequence-mismatch.md
    - Gamma Calibration: stimuli/gamma-calibration.md
  - Hardware:
    - Hardware Overview: hardware-overview.md
    - Behavioral: hardware/behavior_training.md
    - SLAP2: hardware/allen_institute_slap2_hardware.md
    - Neuropixels: hardware/allen_institute_neuropixels_hardware.md
    - Mesoscope: hardware/allen_institute_mesoscope_hardware.md
  - Templates:
    - Experiment Template: template-files/mouse_experiment_template.md
    - Meeting Template: template-files/meeting_template.md
  - Analysis:
    - SLAP2 pilot data analysis: pilotanalysis.md
    - SLAP2 pilot notebook: notebooks/pilot_analysis_rfs.ipynb
  - Experiments:
    - allen_institute:
      - slap2:
        - allen_institute_787727_2025-03-27: experiments/allen_institute/slap2/allen_institute_787727_2025-03-27.md
        - allen_institute_794237_2025-04-03: experiments/allen_institute/slap2/allen_institute_794237_2025-04-03.md
        - allen_institute_794237_2025-04-24: experiments/allen_institute/slap2/allen_institute_794237_2025-04-24.md
        - allen_institute_794237_2025-05-08: experiments/allen_institute/slap2/allen_institute_794237_2025-05-08.md
        - allen_institute_NA_2025-03-20: experiments/allen_institute/slap2/allen_institute_NA_2025-03-20.md
- Project Management:
  - Team: people.md
  - How to Contribute: how_to_contribute.md
  - Collaboration Policy: collaboration-policy.md
  - Project Tracking: project-tracking.md
  - Meetings:
    - '2025-04-21': meetings/2025-04-21.md
    - '2025-05-06': meetings/2025-05-06.md
    - '2025-05-13': meetings/2025-05-13.md
- FAQ: faq.md
theme:
  name: readthedocs
docs_dir: docs
plugins:
- search
- mkdocs-jupyter
edit_uri: https://github.com/allenneuraldynamics/openscope-community-predictive-processing/edit/main/docs/
extra_css:
- custom.css
extra_javascript:
- js/discussion-links.js
- js/github-profiles.js
- js/analytics.js
- https://www.googletagmanager.com/gtag/js?id=G-DT93KEXV5Q
strict: true
dev_addr: 127.0.0.1:8000
