site_name: OpenScope Community Predictive Processing
site_url: https://allenneuraldynamics.github.io/openscope-community-predictive-processing/

nav:
  - Home: index.md
  - Experimental Plan: 
      - Overview: experimental-plan.md
      - Detailed Plan: detailed-experimental-plan.md
  - Project Resources:
      - Hardware Overview: hardware-overview.md
      - Hardware:
          - SLAP2: hardware/allen_institute_slap2_hardware.md
          - Neuropixels: hardware/allen_institute_neuropixels_hardware.md
          - Mesoscope: hardware/allen_institute_mesoscope_hardware.md
      - Stimuli:
          - Bonsai Instructions: stimuli/bonsai_instructions.md
          - Script Details: stimuli/script-details.md
  - Team: people.md
  - Contribute:
      - How to Contribute: how_to_contribute.md
      - Collaboration Policy: collaboration-policy.md
      - Project Tracking: project-tracking.md
      - Templates:
          - Experiment Template: templates/mouse_experiment_template.md
          - Meeting Template: templates/meeting_template.md
  - FAQ: faq.md
  - Meetings: []
  - Experiments: []
theme:
  name: readthedocs

docs_dir: docs

plugins:
  - search

# Add this line to enable the "Edit this page" button
edit_uri: "https://github.com/allenneuraldynamics/openscope-community-predictive-processing/edit/main/docs/"

# Extra CSS files
extra_css:
  - custom.css