site_name: OpenScope Community Predictive Processing
site_url: https://allenneuraldynamics.github.io/openscope-community-predictive-processing/

nav:
  - Home: index.md
  - About the Project: project-tracking.md
  - Collaboration Policy: collaboration-policy.md
  - How to Contribute: how_to_contribute.md
  - Experiments: []
  - Meetings: []
  - Hardware:
      - Neuropixels Hardware: hardware/allen_institute_neuropixels_hardware.md
  - Stimuli Instructions: stimuli/bonsai_instructions.md

theme:
  name: readthedocs

docs_dir: docs

plugins:
  - search

# Add this line to enable the "Edit this page" button
edit_uri: "edit/main/docs/"