name: Sync Discussion Links

on:
  # Run when new discussions are created or updated
  discussion:
    types: [created, edited, deleted]
  
  # Run when markdown files are updated
  push:
    paths:
      - 'docs/**/*.md'
    branches:
      - main
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run weekly to catch any missed updates
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC

jobs:
  sync-discussion-links:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      discussions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run discussion link sync
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python sync_discussion_links.py
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code docs/ || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Auto-sync discussion links

        - Updated discussion links in markdown files
        - Synced with latest GitHub discussions
        - Generated by sync_discussion_links.py"
        git push
    
    - name: Summary
      run: |
        if [ "${{ steps.git-check.outputs.changes }}" = "true" ]; then
          echo "✅ Discussion links were updated and committed"
        else
          echo "⚪ No discussion link updates needed"
        fi
